version: '3.9'

services:
  app:
    build: .
    image: mdi
    command: sh -c "flask fab create-db && flask data && flask run --host=0.0.0.0"
    environment:
      FLASK_APP: app/__init__.py
    ports:
      - ${MINI_DATA_PORT:-8000}:5000
    volumes:
      - ./mdi:/mdi
